CREATE TABLE FirstSeats(sid integer, Lwin char, Laisle char, Raisle char, Rwin char)
CREATE TABLE EconomySeats(sid integer, Lwin char, Lcenter char, Laisle char, Raisle char, Rcenter char, Rwin char)
INSERT INTO FirstSeats VALUES(1, 'A', 'A', 'A', 'A')
INSERT INTO FirstSeats VALUES(2, 'A', 'A', 'A', 'A')
INSERT INTO FirstSeats VALUES(3, 'A', 'A', 'A', 'A')
INSERT INTO FirstSeats VALUES(4, 'A', 'A', 'A', 'A')
INSERT INTO FirstSeats VALUES(5, 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(6, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(7, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(8, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(9, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(10, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(11, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(12, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(13, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(14, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(15, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(16, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(17, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(18, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(19, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(20, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(21, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(22, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(23, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(24, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(25, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(26, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(27, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(28, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(29, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(30, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(31, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(32, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(33, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(34, 'A', 'A', 'A', 'A', 'A', 'A')
INSERT INTO EconomySeats VALUES(35, 'A', 'A', 'A', 'A', 'A', 'A')

